name: Continuous Integration

on:
  push:
    branches:
      - '**'
      # - $default-branch
  pull_request:
    branches:
      - '**'
      # - $default-branch

jobs:
  build:
    env:
      COVER: true
    runs-on: ubuntu-20.04
    steps:
