name: Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version for new release'
        required: true

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v3
      with:
        ref: master
        fetch-depth: 0
        fetch-tags: true

    - name: Prepare Github Actions Bot
      run: |
        git config --local user.name "github-actions[bot]"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
